Repository emiratee/EVAPP, pull requests merged in 2023-11, with the labels that each got.

#2 feat: result cards & result info page started
  Client/.gitignore
  Client/app.json
  Client/app/(tabs)/_layout.tsx
  Client/app/(tabs)/index.tsx
  Client/app/(tabs)/three.tsx
  Client/app/(tabs)/two.tsx
  Client/app/+html.tsx
  Client/app/TripInfo.tsx
  Client/app/[...missing].tsx
  Client/app/_layout.tsx
  Client/app/modal.tsx
  Client/assets/fonts/SpaceMono-Regular.ttf
  Client/assets/images/adaptive-icon.png
  Client/assets/images/driver.png
  Client/assets/images/favicon.png
  Client/assets/images/icon.png
  Client/assets/images/splash.png
  Client/babel.config.js
  Client/components/EditScreenInfo.tsx
  Client/components/ExternalLink.tsx
  Client/components/StyledText.tsx
  Client/components/Themed.tsx
  Client/components/TripCard/TripCard.tsx
  Client/components/__tests__/StyledText-test.js
  Client/constants/Colors.ts
  Client/metro.config.js
  Client/package-lock.json
  Client/package.json
  Client/tsconfig.json
  pla.excalidraw
Labels: Feature, Frontend

#9 feat: TripInfo Modal
  Client/app/(tabs)/t3.tsx
  Client/app/TripInfo.tsx
  Client/components/TripCard/TripCard.tsx
  Client/package-lock.json
  Client/package.json
  pla.excalidraw
Labels: Feature, Frontend

#14 Feat/ add Bill component && temporary addCredits page
  Client/app/(tabs)/addCredits.tsx
  Client/app/(tabs)/search.tsx
  Client/app/TripInfo.tsx
  Client/components/Bill.tsx
Labels: Feature, Frontend

#16 Feat: Simple Backend
  .gitignore
  pla.excalidraw
  server/.gitignore
  server/controllers/tripController.ts
  server/controllers/userController.ts
  server/dist/controllers/tripController.js
  server/dist/controllers/userController.js
  server/dist/index.js
  server/dist/models/Car.js
  server/dist/models/Trip.js
  server/dist/models/User.js
  server/dist/models/db.js
  server/dist/router.js
  server/dist/utils/userUtils.js
  server/index.ts
  server/models/Car.ts
  server/models/Trip.ts
  server/models/User.ts
  server/models/db.ts
  server/package-lock.json
  server/package.json
  server/router.ts
  server/tsconfig.json
  server/utils/userUtils.ts
Labels: Feature, Backend

#18 feat: simple scripts
  package.json
  server/.gitignore
Labels: Feature, Backend, Frontend

#21 feat: Search thing
  Client/.env
  Client/app/(tabs)/TripCardRedirect.tsx
  Client/app/(tabs)/_layout.tsx
  Client/app/(tabs)/search.tsx
  Client/app/(tabs)/two.tsx
  Client/app/TripInfo.tsx
  Client/components/TripCard/TripCard.tsx
  Client/utils/apiService.ts
  server/controllers/tripController.ts
  server/controllers/userController.ts
  server/dist/controllers/tripController.js
  server/dist/controllers/userController.js
  server/dist/models/User.js
  server/dist/router.js
  server/models/User.ts
  server/router.ts
Labels: Feature, Backend, Frontend

#23 Fix/card
  Client/.env
  Client/app/(tabs)/addTrip.tsx
  Client/components/TripCard/TripCard.tsx
  server/dist/controllers/tripController.js
  server/dist/controllers/userController.js
  server/dist/index.js
  server/dist/models/Car.js
  server/dist/models/Trip.js
  server/dist/models/User.js
  server/dist/models/db.js
  server/dist/router.js
  server/dist/utils/userUtils.js
Labels: enhancement, Frontend

#30 Reworking
  Client/app/TripInfo.tsx
  Client/components/Bill.tsx
Labels: Feature, Frontend

#32 Refactor
  Client/app/(tabs)/addCredits.tsx
  Client/app/TripInfo.tsx
  Client/components/Bill.tsx
  Client/utils/apiService.ts
  server/controllers/userController.ts
  server/router.ts
Labels: bug, Feature, Backend, Frontend

#37 Refactored whole history
  Client/app/(tabs)/_layout.tsx
  Client/app/(tabs)/history.tsx
  Client/app/(tabs)/index.tsx
  Client/app/(tabs)/search.tsx
  Client/app/BookRequest.tsx
  Client/app/TripInfo.tsx
  Client/app/_layout.tsx
  Client/app/modal.tsx
  Client/components/HistoryItem.tsx
  Client/components/TripCard/TripCard.tsx
  server/controllers/tripController.ts
  server/controllers/userController.ts
Labels: enhancement, Backend, Frontend

#40 Feat/ add updateAccount method - for now only for password
  Client/app/(tabs)/profile.tsx
  Client/components/ChangePasswordForm.tsx
  Client/utils/apiService.ts
  server/controllers/userController.ts
  server/router.ts
Labels: enhancement, Backend, Frontend
